#!/usr/bin/env python3
"""
Plot training loss curves from CSV files or log files.

Usage:
    # Plot from CSV files (generated by train_gpt.py / train_gpt_linear.py):
    python plot_losses.py logs/run1_losses.csv logs/run2_losses.csv

    # Plot from log files (parses step:N train_loss:X lines):
    python plot_losses.py logs/run1.txt logs/run2.txt

    # Mix both:
    python plot_losses.py logs/run1_losses.csv logs/run2.txt

    # Plot vs wall-clock time instead of steps:
    python plot_losses.py --x-axis time logs/*.csv

    # Save to file instead of showing:
    python plot_losses.py -o comparison.png logs/*.csv
"""

import argparse
import csv
import re
import sys
from pathlib import Path

import matplotlib.pyplot as plt


def parse_csv(path: Path) -> list[dict]:
    rows = []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append({
                "step": int(row["step"]),
                "train_loss": float(row["train_loss"]),
                "elapsed_ms": float(row["elapsed_ms"]),
            })
    return rows


def parse_log(path: Path) -> list[dict]:
    rows = []
    pattern = re.compile(
        r"step:(\d+)/\d+\s+train_loss:([\d.]+)\s+train_time:([\d.]+)ms"
    )
    with open(path) as f:
        for line in f:
            m = pattern.search(line)
            if m:
                rows.append({
                    "step": int(m.group(1)),
                    "train_loss": float(m.group(2)),
                    "elapsed_ms": float(m.group(3)),
                })
    return rows


def load_file(path: Path) -> tuple[str, list[dict]]:
    name = path.stem
    if name.endswith("_losses"):
        name = name[:-7]
    if path.suffix == ".csv":
        return name, parse_csv(path)
    else:
        return name, parse_log(path)


def main():
    parser = argparse.ArgumentParser(description="Plot training loss curves")
    parser.add_argument("files", nargs="+", help="CSV or log files to plot")
    parser.add_argument("--x-axis", choices=["step", "time"], default="step",
                        help="X axis: step number or wall-clock time (default: step)")
    parser.add_argument("-o", "--output", help="Save to file instead of showing")
    parser.add_argument("--ymin", type=float, help="Y axis minimum")
    parser.add_argument("--ymax", type=float, help="Y axis maximum")
    parser.add_argument("--smooth", type=int, default=0,
                        help="Exponential moving average window (0=none)")
    args = parser.parse_args()

    fig, ax = plt.subplots(figsize=(12, 6))

    for filepath in args.files:
        path = Path(filepath)
        if not path.exists():
            print(f"Warning: {path} not found, skipping", file=sys.stderr)
            continue

        name, rows = load_file(path)
        if not rows:
            print(f"Warning: no data in {path}, skipping", file=sys.stderr)
            continue

        steps = [r["step"] for r in rows]
        losses = [r["train_loss"] for r in rows]
        times = [r["elapsed_ms"] / 1000.0 for r in rows]

        if args.smooth > 0:
            alpha = 2.0 / (args.smooth + 1)
            smoothed = [losses[0]]
            for l in losses[1:]:
                smoothed.append(alpha * l + (1 - alpha) * smoothed[-1])
            losses = smoothed

        x = times if args.x_axis == "time" else steps
        ax.plot(x, losses, label=name, linewidth=1.0)

    xlabel = "Wall-clock time (s)" if args.x_axis == "time" else "Step"
    ax.set_xlabel(xlabel)
    ax.set_ylabel("Train Loss")
    ax.set_title("Training Loss Comparison")
    ax.legend()
    ax.grid(True, alpha=0.3)

    if args.ymin is not None or args.ymax is not None:
        ax.set_ylim(bottom=args.ymin, top=args.ymax)

    plt.tight_layout()

    if args.output:
        fig.savefig(args.output, dpi=150)
        print(f"Saved to {args.output}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
